# Generated by Django 4.2.6 on 2024-06-08 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0034_twosteplogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
