# Generated by Django 4.2.6 on 2024-06-08 14:17
import uuid

from django.db import migrations, transaction

from rodManager.dir_models.account import Account


def gen_uuid(apps, schema_editor):
    Account = apps.get_model("rodManager", "Account")
    for account in Account.objects.all():
        account.uid = uuid.uuid4()
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rodManager', '0035_account_uid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
