version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver_plus --cert-file server.cert.pem --key-file server.key.pem 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/
      - ./ca/certs/:/certs/
      - cert_volume:/certs
      - media_volume:/media
    env_file:
      - ./.env.dev
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./ca/certs/:/certs/
      - ./mediafiles:/home/app/web/mediafiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
  angular-app:
    build:
      context: ./rod-manager-ui
      dockerfile: Dockerfile
    volumes:
      - ./ca/certs/:/certs/
    ports:
      - "4200:443" # Expose port 4200 (or any other port you wish to use)
    depends_on:
      - web # Replace with the name of your Django service

volumes:
  postgres_data:
  media_volume:
  cert_volume:
